### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by companje** [PlanBCode/parametric-SVG-editor#23]
After making some mistake in my svg code I got a parser error which became the contents of the textarea resulting in losing my svg xml. Screenshot: http://imgur.com/KYNUo

&lt;parsererror xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black&quot;&gt;&lt;h3&gt;This page contains the following errors:&lt;/h3&gt;&lt;div style=&quot;font-family:monospace;font-size:12px&quot;&gt;error on line 3 at column 27: AttValue: &quot; or ' expected
&lt;/div&gt;&lt;h3&gt;Below is a rendering of the page up to the first error.&lt;/h3&gt;&lt;/parsererror&gt;&lt;rect x=&quot;0&quot; y=&quot;0&quot; rx=&quot;{rounding}&quot; width=&quot;{width}&quot; height=&quot;{height}&quot; mill=&quot;{mill}&quot; style=&quot;fill:none;stroke:red&quot;/&gt;

**Comment by peteruithoven** [comment]
Apparently firefox and chrome give other error messages so now I check for both cases.
It will now give a alert display warning you about the error and explaining that your code will not be stored while you have this error. 
Didn't check other browsers yet.
